### ISSUE TITLE
lib build failed for CAN devices

### ISSUE THREAD

**Issue by gicking** [bschwand/STM8-SPL-SDCC#1]
hi Bruno,

just checked this repo. Nice work! :-)

I added all required .mk files and fixed a few minor bugs. Now the libs can be created for all of the supported STM8A/S devices.

Stupid question: how can I send them to you? So far I only worked on my repos, and I have no idea how to upload them to yours... For your advice thanks a lot in advance!

Georg

**Comment by bschwand** [comment]
hey that is great, thanks.
I assume you cloned my repo, then made a branch, comitted your changes in that branch and pushed the branch. Now you just need to create a pull request for that. https://help.github.com/articles/creating-a-pull-request/
then I can review and merge it in.

**Comment by gicking** [comment]
PS: you also asked [here](https://github.com/gicking/STM8-SPL_SDCC_patch/issues/1) for SPL patches for other devices than STM8A/S. Yes you are correct: on the STM homepage I found SPLs for 4 different STM8 families (STM8L10x, STM8L15x-16x-05x-AL31-L, STM8S, and STM8TL5x). The respective patches are all available from [https://github.com/gicking/STM8-SPL_SDCC_patch](https://github.com/gicking/STM8-SPL_SDCC_patch)

**Comment by gicking** [comment]
you mean create a clone on Github or clone it to my harddisk?

**Comment by bschwand** [comment]
actually, I think the better was is actually to fork the project, then you do a new branch in your forked project, and create a PR from there.
https://help.github.com/articles/creating-a-pull-request-from-a-fork/

This way you do not need any special access to the original repo. I am a git user, but still figuring a bit github...

**Comment by gicking** [comment]
ok, understood. I'm now trying to find out how to fork a project...

**Comment by gicking** [comment]
ah, press the fat "Fork" button... ;-)
