### ISSUE TITLE
SPL licence has been updated 

### ISSUE THREAD

**Issue by gicking** [bschwand/STM8-SPL-SDCC#4]
hello Bruno,

I just saw that the SPL license you cite ([SLA044](http://www.st.com/SLA0044)) does not match the one on the [SPL download](http://www.st.com/content/st_com/en/products/embedded-software/mcus-embedded-software/stm8-embedded-software/stsw-stm8030.html) page ([SLA0048](http://www.st.com/content/ccc/resource/legal/legal_agreement/license_agreement/group0/39/50/32/6c/e0/a8/45/2d/DM00218346/files/DM00218346.pdf/jcr:content/translations/en.DM00218346.pdf)). Maybe this is due to the aforementioned application of a more libarel license by STM...?  

Georg

**Comment by bschwand** [comment]
well that is the file Laurent Desseignes referred me to. I think the situation is kind of messy, with some license referenced in the files, ST apparently having another V2 more liberal license... basically, when they clean up their site, I'll go over and change the mentions in the source files and the link to the right license. I just comply with what ST told me, to be safe.

```
...That is completely ok. Referred license will be updated during a next maintenance operation anyway, but there is no official plan for next release yet.
 
To be on the safe side, you can simply state in headers (or doc, whatever) that the source file is usable under the terms of SL0044, available at URL www.st.com/SLA0044
 
Ty
Rgds
Laurent
```

**Comment by gicking** [comment]
ok, understood. Just bear that in mind and check from time to time
